FROM golang:1.23-bookworm

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN groupadd --gid 10001 wgslirp-test \
    && useradd --uid 10001 --gid wgslirp-test --create-home wgslirp-test

ENV GOCACHE=/tmp/go-build

USER wgslirp-test

ENTRYPOINT ["go", "test"]
